theme: jekyll-theme-cayman
title: Uncovering the genomic determinants of drug resistance in multiple eukaryotic organisms
description: A portfolio from my graduate work in the Winzeler Lab at UCSD
logo: https://avatars1.githubusercontent.com/u/50251155?s=460&v=4
