theme: jekyll-theme-cayman
title: Using experimental evolution to understand the genomic determinants of drug resistance
description: A portfolio of my graduate work in the Winzeler Lab at UC San Diego
