theme: jekyll-theme-cayman
title: Understanding the genomic determinants of drug resistance in parasites
description: A portfolio of my graduate work in the Winzeler Lab at UCSD using experimental evolution and genomics approaches to identify drug targets and resistance mechanisms in multiple eukaryotic pathogens
